version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container_pro
    environment:
      POSTGRES_USER: demouser        
      POSTGRES_PASSWORD: password   
      POSTGRES_DB: demodb      
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data:
    driver: local
