import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/custom/ModeToggle";
import "./globals.css";
import { Toaster } from "sonner";
import QueryProvider from "./providers/QueryProvider";
import { UserProvider } from "./dashboard/context/UserContext";
import { YearBatchProvider } from "./dashboard/context/YearBatchContext";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-white dark:bg-black text-black dark:text-white`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>
            <UserProvider>
              <YearBatchProvider>
                {/* Global dark/light toggle */}
                <div className="top-3 right-4 z-50 fixed">
                  <ModeToggle />
                </div>
                {/* Page content */}
                <main>{children}</main>
                <Toaster />
              </YearBatchProvider>
            </UserProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
