"""Added database model

Revision ID: 1be6ccdef703
Revises: 
Create Date: 2025-04-23 16:53:05.463280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be6ccdef703'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('HOD', 'Timetable_Coordinator', 'Lecturer', name='roleenum'), nullable=False),
    sa.Column('oauth_provider', sa.String(length=50), nullable=False),
    sa.Column('oauth_id', sa.String(length=100), nullable=False),
    sa.Column('joining_year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('oauth_id')
    )
    op.create_table('academicyears',
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('year_id')
    )
    op.create_table('batches',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=10), nullable=False),
    sa.Column('noOfStudent', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['year_id'], ['academicyears.year_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('subjects',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=255), nullable=False),
    sa.Column('subject_code', sa.String(length=100), nullable=False),
    sa.Column('subject_type', sa.Enum('core', 'elective', 'lab', name='subjecttypeenum'), nullable=False),
    sa.Column('no_of_hours_required', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['year_id'], ['academicyears.year_id'], ),
    sa.PrimaryKeyConstraint('subject_id'),
    sa.UniqueConstraint('subject_code')
    )
    op.create_table('workflowstatus',
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('workflow_step', sa.Enum('STEP_1_CREATE_YEAR_AND_BATCH', 'STEP_2_SUBJECT_MANAGEMENT', 'STEP_3_SUBJECT_PRIORITY_FORM', 'STEP_4_PRIORITY_SELECTION', 'STEP_5_AUTO_SUBJECT_ASSIGNMENT_AND_SEND_TO_HOD', 'STEP_6_HOD_REVIEW_AND_APPROVAL', 'STEP_7_FINALIZE_SUBJECT_ALLOCATION', 'STEP_8_TIMETABLE_CREATION', 'STEP_9_TIMETABLE_FORMAT_REVIEW_AND_FINALIZE', 'STEP_10_AUTOGENERATE_TIMETABLE_AND_SEND_TO_HOD', 'STEP_11_HOD_EDIT_AND_UPDATE_TIMETABLE', 'STEP_12_TIMETABLE_FINALIZATION', name='workflowstageenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['year_id'], ['academicyears.year_id'], ),
    sa.PrimaryKeyConstraint('workflow_id'),
    sa.UniqueConstraint('year_id', name='uq_year_workflow')
    )
    op.create_table('lecturerpreferences',
    sa.Column('preference_id', sa.Integer(), nullable=False),
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.Column('selected_sub_id', sa.Integer(), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lecturer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['selected_sub_id'], ['subjects.subject_id'], ),
    sa.ForeignKeyConstraint(['year_id'], ['academicyears.year_id'], ),
    sa.PrimaryKeyConstraint('preference_id'),
    sa.UniqueConstraint('lecturer_id', 'selected_sub_id', 'year_id', name='uq_preference')
    )
    op.create_table('lecturersubassignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Approved', 'Rejected', name='approvalstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academicyears.year_id'], ),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['lecturer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('timetablehourformats',
    sa.Column('format_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('format_data', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('format_id')
    )
    op.create_table('timetable',
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('format_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('time_slot', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['format_id'], ['timetablehourformats.format_id'], ),
    sa.ForeignKeyConstraint(['lecturer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('timetable_id'),
    sa.UniqueConstraint('batch_id', 'day', 'time_slot', name='uq_batch_day_slot')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetable')
    op.drop_table('timetablehourformats')
    op.drop_table('lecturersubassignments')
    op.drop_table('lecturerpreferences')
    op.drop_table('workflowstatus')
    op.drop_table('subjects')
    op.drop_table('batches')
    op.drop_table('academicyears')
    op.drop_table('users')
    # ### end Alembic commands ###
