"""Updated relationship constraints

Revision ID: d8a7f93878ae
Revises: 1be6ccdef703
Create Date: 2025-04-25 14:43:52.171710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a7f93878ae'
down_revision: Union[str, None] = '1be6ccdef703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('academicyears_created_by_fkey', 'academicyears', type_='foreignkey')
    op.create_foreign_key(None, 'academicyears', 'users', ['created_by'], ['user_id'], ondelete='RESTRICT')
    op.drop_constraint('batches_year_id_fkey', 'batches', type_='foreignkey')
    op.drop_constraint('batches_created_by_fkey', 'batches', type_='foreignkey')
    op.create_foreign_key(None, 'batches', 'academicyears', ['year_id'], ['year_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'batches', 'users', ['created_by'], ['user_id'], ondelete='RESTRICT')
    op.drop_constraint('lecturerpreferences_selected_sub_id_fkey', 'lecturerpreferences', type_='foreignkey')
    op.drop_constraint('lecturerpreferences_year_id_fkey', 'lecturerpreferences', type_='foreignkey')
    op.drop_constraint('lecturerpreferences_lecturer_id_fkey', 'lecturerpreferences', type_='foreignkey')
    op.create_foreign_key(None, 'lecturerpreferences', 'academicyears', ['year_id'], ['year_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'lecturerpreferences', 'subjects', ['selected_sub_id'], ['subject_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'lecturerpreferences', 'users', ['lecturer_id'], ['user_id'], ondelete='RESTRICT')
    op.drop_constraint('lecturersubassignments_assigned_by_fkey', 'lecturersubassignments', type_='foreignkey')
    op.drop_constraint('lecturersubassignments_subject_id_fkey', 'lecturersubassignments', type_='foreignkey')
    op.drop_constraint('lecturersubassignments_lecturer_id_fkey', 'lecturersubassignments', type_='foreignkey')
    op.drop_constraint('lecturersubassignments_academic_year_id_fkey', 'lecturersubassignments', type_='foreignkey')
    op.drop_constraint('lecturersubassignments_batch_id_fkey', 'lecturersubassignments', type_='foreignkey')
    op.create_foreign_key(None, 'lecturersubassignments', 'users', ['lecturer_id'], ['user_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'lecturersubassignments', 'academicyears', ['academic_year_id'], ['year_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'lecturersubassignments', 'batches', ['batch_id'], ['batch_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'lecturersubassignments', 'users', ['assigned_by'], ['user_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'lecturersubassignments', 'subjects', ['subject_id'], ['subject_id'], ondelete='RESTRICT')
    op.drop_constraint('subjects_subject_code_key', 'subjects', type_='unique')
    op.create_index(op.f('ix_subjects_subject_code'), 'subjects', ['subject_code'], unique=True)
    op.drop_constraint('subjects_created_by_fkey', 'subjects', type_='foreignkey')
    op.drop_constraint('subjects_year_id_fkey', 'subjects', type_='foreignkey')
    op.create_foreign_key(None, 'subjects', 'users', ['created_by'], ['user_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'subjects', 'academicyears', ['year_id'], ['year_id'], ondelete='RESTRICT')
    op.drop_constraint('timetable_lecturer_id_fkey', 'timetable', type_='foreignkey')
    op.drop_constraint('timetable_created_by_fkey', 'timetable', type_='foreignkey')
    op.drop_constraint('timetable_batch_id_fkey', 'timetable', type_='foreignkey')
    op.drop_constraint('timetable_subject_id_fkey', 'timetable', type_='foreignkey')
    op.drop_constraint('timetable_format_id_fkey', 'timetable', type_='foreignkey')
    op.create_foreign_key(None, 'timetable', 'users', ['created_by'], ['user_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'timetable', 'batches', ['batch_id'], ['batch_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'timetable', 'subjects', ['subject_id'], ['subject_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'timetable', 'timetablehourformats', ['format_id'], ['format_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'timetable', 'users', ['lecturer_id'], ['user_id'], ondelete='RESTRICT')
    op.drop_constraint('timetablehourformats_batch_id_fkey', 'timetablehourformats', type_='foreignkey')
    op.drop_constraint('timetablehourformats_created_by_fkey', 'timetablehourformats', type_='foreignkey')
    op.create_foreign_key(None, 'timetablehourformats', 'users', ['created_by'], ['user_id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'timetablehourformats', 'batches', ['batch_id'], ['batch_id'], ondelete='RESTRICT')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint('workflowstatus_year_id_fkey', 'workflowstatus', type_='foreignkey')
    op.create_foreign_key(None, 'workflowstatus', 'academicyears', ['year_id'], ['year_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflowstatus', type_='foreignkey')
    op.create_foreign_key('workflowstatus_year_id_fkey', 'workflowstatus', 'academicyears', ['year_id'], ['year_id'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_constraint(None, 'timetablehourformats', type_='foreignkey')
    op.drop_constraint(None, 'timetablehourformats', type_='foreignkey')
    op.create_foreign_key('timetablehourformats_created_by_fkey', 'timetablehourformats', 'users', ['created_by'], ['user_id'])
    op.create_foreign_key('timetablehourformats_batch_id_fkey', 'timetablehourformats', 'batches', ['batch_id'], ['batch_id'])
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.create_foreign_key('timetable_format_id_fkey', 'timetable', 'timetablehourformats', ['format_id'], ['format_id'])
    op.create_foreign_key('timetable_subject_id_fkey', 'timetable', 'subjects', ['subject_id'], ['subject_id'])
    op.create_foreign_key('timetable_batch_id_fkey', 'timetable', 'batches', ['batch_id'], ['batch_id'])
    op.create_foreign_key('timetable_created_by_fkey', 'timetable', 'users', ['created_by'], ['user_id'])
    op.create_foreign_key('timetable_lecturer_id_fkey', 'timetable', 'users', ['lecturer_id'], ['user_id'])
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.create_foreign_key('subjects_year_id_fkey', 'subjects', 'academicyears', ['year_id'], ['year_id'])
    op.create_foreign_key('subjects_created_by_fkey', 'subjects', 'users', ['created_by'], ['user_id'])
    op.drop_index(op.f('ix_subjects_subject_code'), table_name='subjects')
    op.create_unique_constraint('subjects_subject_code_key', 'subjects', ['subject_code'])
    op.drop_constraint(None, 'lecturersubassignments', type_='foreignkey')
    op.drop_constraint(None, 'lecturersubassignments', type_='foreignkey')
    op.drop_constraint(None, 'lecturersubassignments', type_='foreignkey')
    op.drop_constraint(None, 'lecturersubassignments', type_='foreignkey')
    op.drop_constraint(None, 'lecturersubassignments', type_='foreignkey')
    op.create_foreign_key('lecturersubassignments_batch_id_fkey', 'lecturersubassignments', 'batches', ['batch_id'], ['batch_id'])
    op.create_foreign_key('lecturersubassignments_academic_year_id_fkey', 'lecturersubassignments', 'academicyears', ['academic_year_id'], ['year_id'])
    op.create_foreign_key('lecturersubassignments_lecturer_id_fkey', 'lecturersubassignments', 'users', ['lecturer_id'], ['user_id'])
    op.create_foreign_key('lecturersubassignments_subject_id_fkey', 'lecturersubassignments', 'subjects', ['subject_id'], ['subject_id'])
    op.create_foreign_key('lecturersubassignments_assigned_by_fkey', 'lecturersubassignments', 'users', ['assigned_by'], ['user_id'])
    op.drop_constraint(None, 'lecturerpreferences', type_='foreignkey')
    op.drop_constraint(None, 'lecturerpreferences', type_='foreignkey')
    op.drop_constraint(None, 'lecturerpreferences', type_='foreignkey')
    op.create_foreign_key('lecturerpreferences_lecturer_id_fkey', 'lecturerpreferences', 'users', ['lecturer_id'], ['user_id'])
    op.create_foreign_key('lecturerpreferences_year_id_fkey', 'lecturerpreferences', 'academicyears', ['year_id'], ['year_id'])
    op.create_foreign_key('lecturerpreferences_selected_sub_id_fkey', 'lecturerpreferences', 'subjects', ['selected_sub_id'], ['subject_id'])
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.create_foreign_key('batches_created_by_fkey', 'batches', 'users', ['created_by'], ['user_id'])
    op.create_foreign_key('batches_year_id_fkey', 'batches', 'academicyears', ['year_id'], ['year_id'])
    op.drop_constraint(None, 'academicyears', type_='foreignkey')
    op.create_foreign_key('academicyears_created_by_fkey', 'academicyears', 'users', ['created_by'], ['user_id'])
    # ### end Alembic commands ###
